from .dashboard import dashboard
from .index import index
from .settings import settings
from .matching import matching
from .chatpage import chatpage
from .login import login
from .check_email import check_email
from .logout import logout
from .dashboard import dashboard
